#ifndef GUARD_KOREAN_GAME_STRINGS_H
#define GUARD_KOREAN_GAME_STRINGS_H

// Auto-generated by tools/korean_glyphs/gen_korean.py -- do not edit.
// Korean for the game's high-frequency UI strings, encoded as extra-symbol
// escapes into the baked Hangul glyph slots. KOREAN_GAME_STRING_LIST pairs
// each one with the English symbol of the same name from include/strings.h.

static const u8 sKorUI_gText_MenuPokedex[] = {0xF9, 0x1B, 0xF9, 0x46, 0xFF}; // 도감
static const u8 sKorUI_gText_MenuPokemon[] = {0xF9, 0x47, 0xF9, 0x48, 0xF9, 0x49, 0xFF}; // 포켓몬
static const u8 sKorUI_gText_MenuBag[] = {0xF9, 0x4A, 0xF9, 0x20, 0xFF}; // 가방
static const u8 sKorUI_gText_MenuSave[] = {0xF9, 0x4B, 0xF9, 0x4C, 0xFF}; // 저장
static const u8 sKorUI_gText_MenuOption[] = {0xF9, 0x18, 0xF9, 0x19, 0xFF}; // 설정
static const u8 sKorUI_gText_MenuExit[] = {0xF9, 0x4D, 0xF9, 0x4A, 0xF9, 0x38, 0xFF}; // 나가기
static const u8 sKorUI_gText_MenuBattleHub[] = {0xF9, 0x4E, 0xF9, 0x4F, 0xFF}; // 허브
static const u8 sKorUI_gText_MenuTradeHub[] = {0xF9, 0x50, 0xF9, 0x51, 0xFF}; // 교환
static const u8 sKorUI_gText_MenuDimensionHole[] = {0xF9, 0x52, 0xF9, 0x53, 0xF9, 0x54, 0xFF}; // 차원홀
static const u8 sKorUI_gText_Yes[] = {0xF9, 0x55, 0xFF}; // 예
static const u8 sKorUI_gText_No[] = {0xF9, 0x56, 0xF9, 0x57, 0xF9, 0x40, 0xFF}; // 아니오
static const u8 sKorUI_gText_PartyMenu_OK[] = {0xF9, 0x58, 0xF9, 0x59, 0xFF}; // 확인
static const u8 sKorUI_gText_OptionMenuCancel[] = {0xF9, 0x2D, 0xF9, 0x22, 0xFF}; // 취소
static const u8 sKorUI_gText_Items[] = {0xF9, 0x1B, 0xF9, 0x5A, 0xFF}; // 도구
static const u8 sKorUI_gText_Items2[] = {0xF9, 0x1B, 0xF9, 0x5A, 0xFF}; // 도구
static const u8 sKorUI_gText_KeyItems[] = {0xF9, 0x5B, 0xF9, 0x5C, 0xF9, 0x1B, 0xF9, 0x5A, 0xFF}; // 중요도구
static const u8 sKorUI_gText_KeyItems2[] = {0xF9, 0x5B, 0xF9, 0x5C, 0xF9, 0x1B, 0xF9, 0x5A, 0xFF}; // 중요도구
static const u8 sKorUI_gText_PokeBalls[] = {0xF9, 0x49, 0xF9, 0x3E, 0xF9, 0x5D, 0xF9, 0x5E, 0xFF}; // 몬스터볼
static const u8 sKorUI_gText_PokeBalls2[] = {0xF9, 0x49, 0xF9, 0x3E, 0xF9, 0x5D, 0xF9, 0x5E, 0xFF}; // 몬스터볼
static const u8 sKorUI_gText_TMCase[] = {0xF9, 0x38, 0xF9, 0x5F, 0xF9, 0x38, 0xF9, 0x60, 0xFF}; // 기술기계
static const u8 sKorUI_gText_TmCase[] = {0xF9, 0x38, 0xF9, 0x5F, 0xF9, 0x38, 0xF9, 0x60, 0xFF}; // 기술기계
static const u8 sKorUI_gText_BerryPouch[] = {0xF9, 0x61, 0xF9, 0x62, 0xFF}; // 열매
static const u8 sKorUI_gText_BerryPouch_2[] = {0xF9, 0x61, 0xF9, 0x62, 0xFF}; // 열매
static const u8 sKorUI_gText_Switch2[] = {0xF9, 0x50, 0xF9, 0x63, 0xFF}; // 교체
static const u8 sKorUI_gText_Summary5[] = {0xF9, 0x64, 0xF9, 0x65, 0xF9, 0x66, 0xFF}; // 능력치
static const u8 sKorUI_gText_Read2[] = {0xF9, 0x67, 0xF9, 0x38, 0xFF}; // 읽기
static const u8 sKorUI_gText_Item[] = {0xF9, 0x1B, 0xF9, 0x5A, 0xFF}; // 도구
static const u8 sKorUI_gText_Mail[] = {0xF9, 0x68, 0xF9, 0x69, 0xFF}; // 편지
static const u8 sKorUI_gText_Take[] = {0xF9, 0x6A, 0xF9, 0x38, 0xFF}; // 받기
static const u8 sKorUI_gText_Store[] = {0xF9, 0x6B, 0xF9, 0x38, 0xF9, 0x38, 0xFF}; // 맡기기
static const u8 sKorUI_gText_Shift[] = {0xF9, 0x50, 0xF9, 0x6C, 0xFF}; // 교대
static const u8 sKorUI_gText_Withdraw[] = {0xF9, 0x6D, 0xF9, 0x6E, 0xF9, 0x38, 0xFF}; // 꺼내기
static const u8 sKorUI_gText_Info[] = {0xF9, 0x19, 0xF9, 0x33, 0xFF}; // 정보
static const u8 sKorUI_gText_Quit[] = {0xF9, 0x6F, 0xF9, 0x70, 0xFF}; // 그만
static const u8 sKorUI_gText_Toss[] = {0xF9, 0x24, 0xF9, 0x23, 0xF9, 0x38, 0xFF}; // 버리기
static const u8 sKorUI_gText_Register[] = {0xF9, 0x71, 0xF9, 0x72, 0xFF}; // 등록
static const u8 sKorUI_gText_Box[] = {0xF9, 0x73, 0xF9, 0x3E, 0xFF}; // 박스
static const u8 sKorUI_gText_ItemEffect_Attack[] = {0xF9, 0x74, 0xF9, 0x75, 0xFF}; // 공격
static const u8 sKorUI_gText_ItemEffect_Defense[] = {0xF9, 0x20, 0xF9, 0x2C, 0xFF}; // 방어
static const u8 sKorUI_gText_ItemEffect_Speed[] = {0xF9, 0x3E, 0xF9, 0x76, 0xF9, 0x27, 0xFF}; // 스피드
static const u8 sKorUI_gText_LevelUp_Attack[] = {0xF9, 0x74, 0xF9, 0x75, 0xFF}; // 공격
static const u8 sKorUI_gText_LevelUp_Defense[] = {0xF9, 0x20, 0xF9, 0x2C, 0xFF}; // 방어
static const u8 sKorUI_gText_TrainerCardMoney[] = {0xF9, 0x22, 0xF9, 0x69, 0xF9, 0x77, 0xFF}; // 소지금
static const u8 sKorUI_gText_Time[] = {0xF9, 0x3A, 0xF9, 0x78, 0xFF}; // 시간
static const u8 sKorUI_gText_Badges[] = {0xF9, 0x79, 0xF9, 0x69, 0xFF}; // 배지
static const u8 sKorUI_gText_Option[] = {0xF9, 0x18, 0xF9, 0x19, 0xFF}; // 설정
static const u8 sKorUI_gText_FrameType[] = {0xF9, 0x7A, 0xF9, 0x7B, 0xFF}; // 타입

#define KOREAN_GAME_STRING_LIST \
    X(gText_MenuPokedex) \
    X(gText_MenuPokemon) \
    X(gText_MenuBag) \
    X(gText_MenuSave) \
    X(gText_MenuOption) \
    X(gText_MenuExit) \
    X(gText_MenuBattleHub) \
    X(gText_MenuTradeHub) \
    X(gText_MenuDimensionHole) \
    X(gText_Yes) \
    X(gText_No) \
    X(gText_PartyMenu_OK) \
    X(gText_OptionMenuCancel) \
    X(gText_Items) \
    X(gText_Items2) \
    X(gText_KeyItems) \
    X(gText_KeyItems2) \
    X(gText_PokeBalls) \
    X(gText_PokeBalls2) \
    X(gText_TMCase) \
    X(gText_TmCase) \
    X(gText_BerryPouch) \
    X(gText_BerryPouch_2) \
    X(gText_Switch2) \
    X(gText_Summary5) \
    X(gText_Read2) \
    X(gText_Item) \
    X(gText_Mail) \
    X(gText_Take) \
    X(gText_Store) \
    X(gText_Shift) \
    X(gText_Withdraw) \
    X(gText_Info) \
    X(gText_Quit) \
    X(gText_Toss) \
    X(gText_Register) \
    X(gText_Box) \
    X(gText_ItemEffect_Attack) \
    X(gText_ItemEffect_Defense) \
    X(gText_ItemEffect_Speed) \
    X(gText_LevelUp_Attack) \
    X(gText_LevelUp_Defense) \
    X(gText_TrainerCardMoney) \
    X(gText_Time) \
    X(gText_Badges) \
    X(gText_Option) \
    X(gText_FrameType) \


#endif // GUARD_KOREAN_GAME_STRINGS_H
