#ifndef GUARD_LANGSELECT_STRINGS_H
#define GUARD_LANGSELECT_STRINGS_H

// Auto-generated by tools scratch gen_korean.py. Native-script names
// (Japanese/Chinese) for the boot language-select screen, baked into
// the normal font's free glyph slots.

static const u8 sLangText_Japanese[] = { 0xF9, 0x41, 0xF9, 0x42, 0xF9, 0x43, 0xFF }; // 日本語
static const u8 sLangText_Chinese[] = { 0xF9, 0x44, 0xF9, 0x45, 0xFF }; // 中文

#endif // GUARD_LANGSELECT_STRINGS_H
